prompt='gps cut value=?';
gpsNumber=input(prompt);
b=gpsNumber-foo;
gpsECEF(1:b,:)=[];
gpsconversion
a=length(ENUGPS)+1;
frontLeftPos(a:end)=[];
% frontLeftPos2(a:end)=[];
frontLeftVel(a:end)=[];
% frontLeftVel2(a:end)=[];
frontRightPos(a:end)=[];
% frontRightPos2(a:end)=[];
frontRightVel(a:end)=[];
% frontRightVel2(a:end)=[];
rearLeftPos(a:end)=[];
% rearLeftPos2(a:end)=[];
rearLeftVel(a:end)=[];
% rearLeftVel2(a:end)=[];
rearRightPos(a:end)=[];
% rearRightPos2(a:end)=[];
rearRightVel(a:end)=[];
% rearRightVel2(a:end)=[];
ang_z(a:end)=[];
lin_x(a:end)=[];
lin_y(a:end)=[];
Pos_x(a:end)=[];
Pos_y(a:end)=[];
tTodom(a:end)=[];
figure;plot(ENUGPS(2,:));hold on; plot(Pos_x);
matTime=find((tTimu>tTodom(end)));
imuCut=matTime(1)-1;
Ax(imuCut:end)=[];
Ay(imuCut:end)=[];
Az(imuCut:end)=[];
Gx(imuCut:end)=[];
Gy(imuCut:end)=[];
Gz(imuCut:end)=[];
tTimu(imuCut:end)=[];

